name: Create Release

on:
  push:
    tags:
      - 'v*'  # déclenché pour les tags comme v1.0.0, v1.2.3, etc.

jobs:
  release:
    name: Create GitHub Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate changelog (basic)
        run: |
          echo "## Changes in ${GITHUB_REF##*/}" > RELEASE_CHANGELOG.md
          git log -1 --pretty=format:"- %s" >> RELEASE_CHANGELOG.md

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ github.ref_name }}
          body_path: RELEASE_CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
